import type { Donation, Nonprofit } from "./types";

export const DEMO_DONOR = "Sunrise Bakery — Fremont (Demo)";
export const DEMO_DRIVER_POOL = ["Priya S. (student volunteer)"];

// Fictional organizations — never real ones.
export const SEED_NONPROFITS: Nonprofit[] = [
  {
    id: "np-meal-program",
    name: "Fremont Community Meal Program (Demo)",
    acceptsPrepared: true,
    acceptsBaked: true,
    acceptsProduce: true,
    hasFridge: true,
    hasFreezer: false,
    dietarySupport: ["vegetarian"],
    openUntil: "9:00 PM",
    maxMeals: 40,
    distanceMiles: 1.4,
    notes: "Accepts prepared vegetarian meals. Can receive until 9 PM.",
  },
  {
    id: "np-harbor-shelter",
    name: "Harbor Light Shelter — Fremont (Demo)",
    acceptsPrepared: true,
    acceptsBaked: true,
    acceptsProduce: false,
    hasFridge: true,
    hasFreezer: true,
    dietarySupport: ["vegetarian", "halal"],
    openUntil: "8:00 PM",
    maxMeals: 60,
    distanceMiles: 2.1,
    notes: "Evening intake until 8 PM. Fridge + freezer on site.",
  },
  {
    id: "np-veg-share",
    name: "Fremont Veg Share Collective (Demo)",
    acceptsPrepared: true,
    acceptsBaked: false,
    acceptsProduce: true,
    hasFridge: false,
    hasFreezer: false,
    dietarySupport: ["vegan"],
    openUntil: "9:30 PM",
    maxMeals: 20,
    distanceMiles: 0.9,
    notes: "Room-temperature vegan food only — no refrigeration.",
  },
  {
    id: "np-faith-kitchen",
    name: "South Fremont Faith Kitchen (Demo)",
    acceptsPrepared: false,
    acceptsBaked: true,
    acceptsProduce: true,
    hasFridge: true,
    hasFreezer: false,
    dietarySupport: ["vegetarian", "nut-free"],
    openUntil: "7:30 PM",
    maxMeals: 30,
    distanceMiles: 2.8,
    notes: "Bakery + produce focus. Nut-free preferred.",
  },
];

export const SEED_DONATIONS: Donation[] = [
  {
    id: "don-seed-bakery",
    title: "10 veg sandwiches + 24 pastries",
    description:
      "10 vegetarian sandwiches and 24 pastries, approximately 15 pounds total. Contains dairy and wheat. Pickup before 8:25 PM. Keep refrigerated.",
    meals: 34,
    pounds: 15,
    category: "prepared + baked",
    dietaryTags: ["vegetarian", "nut-free"],
    allergens: ["dairy", "wheat"],
    storage: "refrigerated",
    pickupDeadline: "8:25 PM",
    pickupLocation: "Sunrise Bakery, Fremont (Demo)",
    pickupNotes: "Pickup through back entrance, ask for the manager.",
    donorName: DEMO_DONOR,
    status: "Available",
    distanceMiles: 1.6,
    etaMinutes: 12,
    createdAt: new Date().toISOString(),
  },
  {
    id: "don-seed-catering",
    title: "14 boxed vegetarian wraps (catering leftover)",
    description:
      "14 boxed vegetarian wraps from a canceled catering order, ~12 lbs. Contains dairy. Keep cold. Pickup by 8:45 PM.",
    meals: 14,
    pounds: 12,
    category: "prepared meals",
    dietaryTags: ["vegetarian"],
    allergens: ["dairy"],
    storage: "refrigerated",
    pickupDeadline: "8:45 PM",
    pickupLocation: "Downtown Fremont café (Demo)",
    pickupNotes: "",
    donorName: "Downtown Fremont Café (Demo)",
    status: "Available",
    distanceMiles: 1.8,
    etaMinutes: 14,
    createdAt: new Date().toISOString(),
  },
];
